package com.example.demo.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "task_entity")
public class TaskEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String taskId;

    @DynamoDBAttribute
    private String fileName;

    @DynamoDBAttribute
    private String originalFilePath;

    @DynamoDBAttribute
    private String rotatedFilePath;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private TaskState taskState;
}